train_ann_path: trashcan_data/trashcan_chunksplit_train_coarse.json
val_ann_path: trashcan_data/trashcan_chunksplit_val_coarse.json
train_img_dir: trashcan_data/images
val_img_dir: trashcan_data/images
checkpoint_dir: checkpoints/trashcan_chunksplit_coarse/model6v2
num_workers: 8
use_torch_compile: false
num_epochs: 50
batch_size: 8
accumulation_steps: 1
use_amp: true
clip_grad_norm: 5.0
optimizer: sgd
lr: 0.005
momentum: 0.9
weight_decay: 0.0001
adam_betas: !!python/tuple
- 0.9
- 0.999
lr_scheduler_type: cosine
lr_milestones: !!python/tuple
- 66
- 88
lr_gamma: 0.1
warmup_epochs: 1
warmup_factor: 0.001
cosine_eta_min: 5.0e-05
num_classes: 6
pretrained: true
use_v1_arch: false
use_group_norm: true
gn_num_groups: 32
freeze_backbone_stages: 2
freeze_backbone_bn: true
backbone_lr_factor: 1.0
backbone_wd_factor: 1.0
use_custom_anchor_generator: true
custom_anchor_sizes: !!python/tuple
- !!python/tuple
  - 16
- !!python/tuple
  - 32
- !!python/tuple
  - 64
- !!python/tuple
  - 128
- !!python/tuple
  - 256
custom_aspect_ratios: !!python/tuple
- !!python/tuple
  - 0.5
  - 1.0
  - 2.0
use_custom_rpn_fg_iou_threshold: false
custom_rpn_fg_iou_threshold: 0.5
use_custom_positive_proposal_fractions: false
custom_rpn_positive_fraction: 0.5
custom_box_positive_fraction: 0.25
min_size: !!python/tuple
- 256
- 288
- 320
- 352
- 384
max_size: 704
use_photometric_distort: false
use_random_erasing: false
use_random_grayscale: false
random_grayscale_prob: 0.2
use_fourier_style_randomization: false
fsr_prob: 0.3
fsr_beta: 0.01
fsr_noise_prob: 0.15
fsr_style_bank_dir: ''
fsr_style_bank_spectra: ''
fsr_style_bank_max_images: 200
use_copy_paste: true
copy_paste_prob: 0.5
copy_paste_max_objects: 3
copy_paste_scale_ranges: !!python/tuple
- !!python/tuple
  - 0.5
  - 0.8
- !!python/tuple
  - 0.8
  - 1.2
copy_paste_scale_range_weights: !!python/tuple
- 0.6
- 0.4
copy_paste_rotation_range: !!python/tuple
- -90
- 90
copy_paste_min_crop_side_length: 16
copy_paste_min_object_area: 128
copy_paste_color_match: true
copy_paste_exclude_cats: !!python/tuple
- 1
dropout_rate: 0.0
mask_dropout_rate: 0.0
label_smoothing: 0.0
tta_enabled: false
tta_flip: true
tta_scales: !!python/tuple
- 1.0
tta_rotation: !!python/tuple
- 0.0
tta_grayscale: false
tta_clahe: false
tta_nms_threshold: 0.5
tta_soft_nms: false
tta_mask_avg: true
print_freq: 50
verbose: true
log_grad_norm: true
